openapi: 3.0.3
info:
  title: Checkout.com - Identity Verification Address document verifications (Coming soon) Address document verifications (Coming soon) Face authentications API
  version: 1.0.0
  x-logo:
    url: https://raw.githubusercontent.com/ubbleai/docs/main/cko_doc_logo.png
  description: ''
servers:
- url: https://api.ubble.ai
tags:
- name: Face authentications
paths:
  /v2/face-authentications:
    post:
      tags:
      - Face authentications
      summary: Create a face authentication
      description: This endpoint allows you to create a face authentication.
      operationId: create_face_authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FaceAuthenticationInputPost'
      responses:
        '201':
          description: Face authentication created
          content:
            application/json:
              examples:
                face_authentication_creation_response_body:
                  $ref: '#/components/examples/face_authentication_creation_response_body'
              schema:
                allOf:
                - $ref: '#/components/schemas/FaceAuthenticationOutputPost'
        '400':
          description: Bad request
        '500':
          description: Internal server error
  /v2/face-authentications/{face_authentication_id}:
    get:
      tags:
      - Face authentications
      summary: Retrieve a face authentication
      description: This endpoint allows you to get the detailed results of a face authentication.
      operationId: retrieve_face_authentication
      parameters:
      - name: face_authentication_id
        required: true
        in: path
        description: ID of the face authentication
        schema:
          $ref: '#/components/schemas/FaceAuthenticationId'
      responses:
        '200':
          description: Face authentication retrieved
          content:
            application/json:
              examples:
                face_authentication_creation_response_body:
                  $ref: '#/components/examples/face_authentication_creation_response_body'
              schema:
                allOf:
                - $ref: '#/components/schemas/FaceAuthenticationOutputGet'
        '404':
          description: Face authentication not found
        '500':
          description: Internal server error
  /v2/face-authentications/{face_authentication_id}/anonymize:
    post:
      tags:
      - Face authentications
      summary: Anonymize a face authentication
      description: Anonymize the personal data of a face authentication with the specified ID.
      operationId: anonymize_face_authentication
      parameters:
      - name: face_authentication_id
        in: path
        description: ID of the face authentication to anonymize
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Face authentication anonymization requested
          content:
            application/json:
              examples:
                face_authentication_anonymization_response_body:
                  $ref: '#/components/examples/face_authentication_anonymization_response_body'
              schema:
                required:
                - applicant_id
                - user_journey_id
                allOf:
                - $ref: '#/components/schemas/FaceAuthenticationOutputAnonymize'
        '404':
          description: Face authentication not found
        '400':
          description: Bad request. The face authentication cannot be anonymized.
        '500':
          description: Internal server error
  /v2/face-authentications/{face_authentication_id}/attempts:
    get:
      tags:
      - Face authentications
      summary: List attempts
      description: 'This endpoint allows you to list all attempts of a face authentication.


        Attempts are returned ordered by creation date, newest first.


        The response is paginated (see [Pagination](#section/API-standards/Pagination) section).

        You can navigate through pages using the `skip` and `limit` query parameters or by following the URLs in the `_links` object.

        '
      operationId: list_attempts_face_authentication
      parameters:
      - name: face_authentication_id
        in: path
        description: ID of the face authentication
        required: true
        schema:
          type: string
      - $ref: '#/components/parameters/skipParam'
      - $ref: '#/components/parameters/limitParam'
      responses:
        '200':
          description: List attempts
          content:
            application/json:
              examples:
                face_authentication_attempt_list_response_body:
                  $ref: '#/components/examples/face_authentication_attempt_list_response_body'
              schema:
                allOf:
                - $ref: '#/components/schemas/FaceAuthenticationAttemptResponseList'
        '404':
          description: The provided face authentication ID is not valid
        '500':
          description: An error occurred while fetching the attempts
    post:
      tags:
      - Face authentications
      summary: Create an attempt
      description: This endpoint allows you to create a new Attempt. It is possible when the face-authentication is in one of the following statuses `created`, `pending`, `capture_in_progress`, `retry_required`
      operationId: create_attempt_face_authentication
      parameters:
      - name: face_authentication_id
        in: path
        description: ID of the face authentication
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            examples:
              Minimal body:
                $ref: '#/components/examples/attempt_creation_request_body_min'
              All possible data:
                $ref: '#/components/examples/face_attempt_creation_request_body_max'
            schema:
              $ref: '#/components/schemas/FaceAuthenticationAttemptInputPost'
      responses:
        '201':
          description: Attempt created
          content:
            application/json:
              examples:
                face_authentication_attempt_creation_response_body:
                  $ref: '#/components/examples/face_authentication_attempt_creation_response_body'
              schema:
                allOf:
                - $ref: '#/components/schemas/FaceAuthenticationAttemptOutputPost'
        '404':
          description: The provided face authentication ID is not valid
        '409':
          description: The current face authentication status does not allow the creation of a new attempt. The face authentication status must be either `created`, `pending`, `capture_in_progress`, or `retry_required`
        '500':
          description: An error occurred while creating the attempt
  /v2/face-authentications/{face_authentication_id}/attempts/{attempt_id}:
    get:
      tags:
      - Face authentications
      summary: Retrieve an attempt
      description: This endpoint allows you to retrieve the details for a given attempt
      operationId: fetch_attempts_face_authentication
      parameters:
      - name: face_authentication_id
        in: path
        description: ID of the face authentication
        required: true
        schema:
          type: string
      - name: attempt_id
        in: path
        description: ID of the attempt
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Attempt fetched
          content:
            application/json:
              examples:
                face_authentication_detail_response_body:
                  $ref: '#/components/examples/face_authentication_attempt_get_response_body'
              schema:
                allOf:
                - $ref: '#/components/schemas/FaceAuthenticationAttemptOutputGet'
        '404':
          description: The provided face authentication ID or attempt ID is not valid
        '500':
          description: An error occurred while fetching the attempt
  /v2/face-authentications/{face_authentication_id}/attempts/{attempt_id}/assets:
    get:
      tags:
      - Face authentications
      summary: Retrieve attempt assets
      description: 'Retrieves the assets associated with a face authentication attempt.

        This includes face images and videos captured during the verification process.

        Please note that videos are not exposed by default, contact your account manager to enable this feature.


        The response is paginated (see [Pagination](#section/API-standards/Pagination) section).

        You can navigate through pages using the `skip` and `limit` query parameters or by following the URLs in the `_links` object.

        '
      operationId: retrieve_face_authentication_attempt_assets
      parameters:
      - name: face_authentication_id
        in: path
        required: true
        schema:
          type: string
        description: The ID of the face authentication
      - name: attempt_id
        in: path
        required: true
        schema:
          type: string
        description: The ID of the attempt
      - $ref: '#/components/parameters/skipParam'
      - $ref: '#/components/parameters/limitParam'
      responses:
        '200':
          description: The assets were retrieved successfully
          content:
            application/json:
              examples:
                face_authentication_attempt_assets_response_body:
                  $ref: '#/components/examples/face_authentication_attempt_assets_response_body'
              schema:
                $ref: '#/components/schemas/FaceAuthenticationAttemptAssetsOutput'
  /v2/face-authentications/{face_authentication_id}/notify:
    post:
      tags:
      - Face authentications
      summary: Request webhook notification
      operationId: notify_face_authentication
      description: This endpoint can be used to initiate a webhook call containing the latest event of a face authentication.
      parameters:
      - name: face_authentication_id
        in: path
        description: ID of the face authentication to notify
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                webhook_url:
                  type: string
                  format: uri
      responses:
        '204':
          description: Notification successfully requested
components:
  schemas:
    PhonePrefix:
      type: string
      format: international phone prefix
      pattern: ^\+(\d+)$
      example: '+33'
    CountryCodeIso2:
      type: string
      format: ISO 3166-1 alpha-2
      pattern: ^[A-Za-z]{2}$
      example: US
    RiskLabels:
      type: array
      items:
        $ref: '#/components/schemas/RiskLabel'
      description: Risk assessment labels
    ActiveLink:
      type: object
      required:
      - verification_url
      properties:
        verification_url:
          $ref: '#/components/schemas/HalLink'
    UserJourneyId:
      type: string
      description: User journey unique identifier.
      pattern: ^usj_\w+$
      example: usj_tkoi5db4hryu5cei5vwoabr7we
    ListLinks:
      type: object
      required:
      - self
      properties:
        self:
          description: Link to the current page
          $ref: '#/components/schemas/HalLink'
        previous:
          description: Link to the previous page (null if on the first page)
          $ref: '#/components/schemas/HalLink'
        next:
          description: Link to the next page (null if on the last page)
          $ref: '#/components/schemas/HalLink'
    FaceAuthenticationAttemptInputBase:
      type: object
      allOf:
      - $ref: '#/components/schemas/FaceAttemptBase'
    FaceAuthenticationAttemptAssetOutput:
      type: object
      required:
      - type
      - _links
      properties:
        type:
          type: string
          enum:
          - face_image
          - face_video
        _links:
          required:
          - asset_url
          type: object
          properties:
            asset_url:
              $ref: '#/components/schemas/HalLink'
    FaceAuthenticationAttemptOutputBase:
      type: object
      properties:
        id:
          type: string
        status:
          $ref: '#/components/schemas/AttemptStates'
        response_codes:
          type: array
          minItems: 0
          items:
            $ref: '#/components/schemas/ResponseCodes'
        applicant_session_information:
          $ref: '#/components/schemas/FaceAuthenticationApplicantSessionInformation'
        _links:
          allOf:
          - $ref: '#/components/schemas/AttemptLinks'
      allOf:
      - $ref: '#/components/schemas/DatedObject'
      - $ref: '#/components/schemas/FaceAttemptBase'
    RiskLabel:
      type: string
      description: Risk assessment label.
      enum:
      - multiple_faces_detected
      - mcc_not_confident
      - risky_document_format
    FaceAuthenticationAttemptAssetsOutput:
      type: object
      required:
      - total_count
      - skip
      - limit
      - _links
      - data
      properties:
        data:
          type: array
          description: Array of face authentication attempt assets for the current page
          minItems: 0
          items:
            $ref: '#/components/schemas/FaceAuthenticationAttemptAssetOutput'
      allOf:
      - $ref: '#/components/schemas/BaseOutputList'
    FaceAuthenticationLinks:
      type: object
      allOf:
      - $ref: '#/components/schemas/SelfLink'
      - $ref: '#/components/schemas/ApplicantLink'
    DomesticPhoneNumber:
      type: string
      format: domestic phone number
      pattern: ^\d{1,14}$
      example: '2068133616'
    FaceAuthenticationAttemptInputPost:
      type: object
      required:
      - redirect_url
      allOf:
      - $ref: '#/components/schemas/FaceAuthenticationAttemptInputBase'
    FaceAuthenticationInputPost:
      type: object
      required:
      - webhook_url
      - applicant_id
      - user_journey_id
      allOf:
      - $ref: '#/components/schemas/FaceAuthenticationInputBase'
    SelfLink:
      type: object
      required:
      - self
      properties:
        self:
          $ref: '#/components/schemas/HalLink'
    ResponseSummary:
      type: string
      description: A descriptive code of the response code.
    FaceAuthenticationApplicantSessionInformation:
      type: object
      allOf:
      - $ref: '#/components/schemas/BaseApplicantSessionInformation'
    FaceAuthenticationAttemptOutputGet:
      type: object
      required:
      - id
      - status
      - redirect_url
      - response_codes
      - _links
      allOf:
      - $ref: '#/components/schemas/FaceAuthenticationAttemptOutputBase'
    FaceAuthenticationOutputAnonymize:
      type: object
      required:
      - id
      - status
      - webhook_url
      - applicant_id
      - user_journey_id
      - response_codes
      - risk_labels
      - _links
      properties:
        face:
          $ref: '#/components/schemas/VerificationFace'
      allOf:
      - $ref: '#/components/schemas/FaceAuthenticationOutputBase'
    AttemptStates:
      type: string
      description: States of an attempt.
      enum:
      - pending_redirection
      - capture_in_progress
      - checks_in_progress
      - completed
      - expired
      - capture_aborted
      - capture_refused
      - checks_inconclusive
      - terminated
    FaceAuthenticationAttemptResponseList:
      type: object
      required:
      - total_count
      - skip
      - limit
      - _links
      - data
      properties:
        data:
          type: array
          description: Array of face authentication attempts for the current page
          minItems: 0
          items:
            $ref: '#/components/schemas/FaceAuthenticationAttemptOutputGet'
      allOf:
      - $ref: '#/components/schemas/BaseOutputList'
    InitialDevices:
      type: string
      description: Initial device which started the session
      enum:
      - mobile
      - desktop
    ResponseCodes:
      type: object
      description: The code giving more details about the result.
      properties:
        code:
          $ref: '#/components/schemas/ResponseCode'
        summary:
          $ref: '#/components/schemas/ResponseSummary'
      required:
      - code
      - summary
    FaceAuthenticationOutputBase:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/FaceAuthenticationId'
        status:
          $ref: '#/components/schemas/VerificationStatuses'
        response_codes:
          type: array
          items:
            $ref: '#/components/schemas/ResponseCodes'
        risk_labels:
          $ref: '#/components/schemas/RiskLabels'
        face:
          $ref: '#/components/schemas/VerificationFace'
        _links:
          $ref: '#/components/schemas/FaceAuthenticationLinks'
      allOf:
      - $ref: '#/components/schemas/FaceAuthenticationBase'
      - $ref: '#/components/schemas/DatedObject'
    ApplicantId:
      type: string
      description: Applicant unique identifier.
      pattern: ^aplt_\w+$
      example: aplt_tkoi5db4hryu5cei5vwoabr7we
    ApplicantLink:
      type: object
      required:
      - applicant
      properties:
        applicant:
          $ref: '#/components/schemas/HalLink'
    FaceAuthenticationOutputPost:
      type: object
      required:
      - id
      - status
      - webhook_url
      - applicant_id
      - response_codes
      - risk_labels
      - user_journey_id
      - _links
      properties:
        face:
          $ref: '#/components/schemas/VerificationFace'
      allOf:
      - $ref: '#/components/schemas/FaceAuthenticationOutputBase'
    ResponseCode:
      type: integer
      description: The numeric code of the response code.
      minimum: 10000
      maximum: 69999
    BaseOutputList:
      type: object
      properties:
        total_count:
          type: integer
          description: Total number of items available across all pages
        skip:
          type: integer
          description: Number of items skipped (offset from the start)
        limit:
          type: integer
          description: Maximum number of items returned in this page
        _links:
          $ref: '#/components/schemas/ListLinks'
    PhoneNumber:
      type: object
      required:
      - country_code
      - number
      properties:
        country_code:
          $ref: '#/components/schemas/PhonePrefix'
        number:
          $ref: '#/components/schemas/DomesticPhoneNumber'
    LanguageCode:
      type: string
      format: IETF BCP 47 language tag
      description: Language tag following IETF BCP 47 standard
      example: en-US
    AttemptLinks:
      type: object
      allOf:
      - $ref: '#/components/schemas/ActiveLink'
      - $ref: '#/components/schemas/SelfLink'
    BaseApplicantSessionInformation:
      type: object
      properties:
        ip_address:
          type: string
          description: Ip address of the applicant during the session
          example: 123:456:789:00
        number_of_sessions:
          type: integer
          description: Number of sessions opened by user
          example: 3
        user_agent:
          type: string
          description: User session user agent
          example: Mozilla/5.0 (Linux; Android 8.0.0; SM-G960F Build/R16NW) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.84 Mobile Safari/537.36
        initial_device:
          $ref: '#/components/schemas/InitialDevices'
    FaceAuthenticationInputBase:
      type: object
      allOf:
      - $ref: '#/components/schemas/FaceAuthenticationBase'
    FaceAttemptBase:
      type: object
      properties:
        phone_number:
          $ref: '#/components/schemas/PhoneNumber'
        client_information:
          $ref: '#/components/schemas/FaceAttemptClientInformation'
        redirect_url:
          type: string
          format: uri
    FaceAuthenticationBase:
      type: object
      properties:
        user_journey_id:
          $ref: '#/components/schemas/UserJourneyId'
        applicant_id:
          $ref: '#/components/schemas/ApplicantId'
        webhook_url:
          type: string
          format: uri
    FaceAuthenticationOutputGet:
      type: object
      required:
      - id
      - status
      - webhook_url
      - applicant_id
      - response_codes
      - risk_labels
      - user_journey_id
      - _links
      allOf:
      - $ref: '#/components/schemas/FaceAuthenticationOutputBase'
    HalLink:
      type: object
      required:
      - href
      properties:
        href:
          type: string
          format: uri
    FaceAttemptClientInformation:
      type: object
      properties:
        pre_selected_residence_country:
          $ref: '#/components/schemas/CountryCodeIso2'
        pre_selected_language:
          $ref: '#/components/schemas/LanguageCode'
    VerificationStatuses:
      type: string
      description: Status of the verification.
      enum:
      - created
      - pending
      - capture_in_progress
      - checks_in_progress
      - approved
      - declined
      - retry_required
      - refused
      - inconclusive
    FaceAuthenticationAttemptOutputPost:
      type: object
      required:
      - id
      - status
      - redirect_url
      - response_codes
      - _links
      allOf:
      - $ref: '#/components/schemas/FaceAuthenticationAttemptOutputBase'
    VerificationFace:
      type: object
      properties:
        image_signed_url:
          type: string
          nullable: true
    DatedObject:
      type: object
      required:
      - created_on
      - modified_on
      properties:
        created_on:
          description: UTC Date time when the resource was created
          type: string
          format: date-time
          example: 2017-07-21 17:32:28+00:00
        modified_on:
          description: UTC Date time when the resource was modified
          type: string
          format: date-time
          example: 2017-07-21 17:40:32+00:00
    FaceAuthenticationId:
      type: string
      description: Face authentication unique identifier.
      pattern: ^fav_\w+$
      example: fav_tkoi5db4hryu5cei5vwoabr7we
  examples:
    face_authentication_attempt_list_response_body:
      value:
        total_count: 2
        skip: 10
        limit: 10
        data:
        - id: fatp_tkoi5db4hryu5cei5vwoabrPoQ
          created_on: 2017-07-21 17:32:28+00:00
          modified_on: 2017-07-21 17:40:32+00:00
          status: checks_in_progress
          response_codes: []
          phone_number:
            country_code: '+1'
            number: '2068133616'
          redirect_url: https://myweb.site?query-param=hello
          client_information:
            pre_selected_residence_country: FR
          applicant_session_information:
            ip_address: 123.123.123.01
          _links:
            verification_url:
              href: https://id.ubble.ai/4hryu5cei5/
            self:
              href: https://api.ubble.ai/face-authentications/4hryu5cei5/fatp_tkoi5db4hryu5cei5vwoabrPoQ
        - id: fatp_tkoi5db4hryu5cei5vwoabriom
          created_on: 2017-07-21 16:30:28+00:00
          modified_on: 2017-07-21 16:32:32+00:00
          status: checks_inconclusive
          response_codes:
          - code: 61402
            summary: face_video_lighting_issue
          phone_number:
            country_code: '+1'
            number: '2068133616'
          redirect_url: https://myweb.site?query-param=hello
          client_information:
            pre_selected_residence_country: FR
          applicant_session_information:
            ip_address: 123.123.123.01
          _links:
            self:
              href: https://api.ubble.ai/v2/face-authentications/fav_tkoi5db4hryu5cei5vwoabr7we/attempts/fatp_tkoi5db4hryu5cei5vwoabr7we
            verification_url:
              href: https://id.ubble.ai/4hryu5clik/
        _links:
          self:
            href: https://api.ubble.ai/v2/face-authentications/fav_tkoi5db4hryu5cei5vwoabr7we/attempts?skip=10&limit=10
          next:
            href: https://api.ubble.ai/v2/face-authentications/fav_tkoi5db4hryu5cei5vwoabr7we/attempts?skip=20&limit=10
          previous:
            href: https://api.ubble.ai/v2/face-authentications/fav_tkoi5db4hryu5cei5vwoabr7we/attempts?skip=0&limit=10
    face_authentication_creation_response_body:
      value:
        id: fav_tkoi5db4hryu5cei5vwoabr7we
        created_on: 2017-07-21 17:32:28+00:00
        modified_on: 2017-07-21 17:40:32+00:00
        user_journey_id: usj_tkoi5db4hryu5cei5vwoabr7we
        applicant_id: aplt_tkoi5db4hryu5cei5vwoabr7we
        status: declined
        response_codes:
        - code: 62403
          summary: consent_unclear
        - code: 61402
          summary: face_video_lighting_issue
        risk_labels:
        - multiple_faces_detected
        face:
          image_signed_url: https://storage-b.env.ubble.ai/ubble-ai/NDYOOVHGZPAQ/a54b3393-f02a-47c9-a9c5-2f6ee73560e1/bb603e2f-5de9-40f2-9631-8285a33c24c0/live_face/bb603e2f-5de9-40f2-9631-8285a33c24c0-1679921946714.png?response-content-type=image%2Fpng&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=V9jgOdpOdeVSFTkA4ZsG%2F20230327%2Feu-west-2%2Fs3%2Faws4_request&X-Amz-Date=20230327T163223Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=2b7d87fec4f11f0df949da7beade2519cf1a51ce70fe9cc1cf0470d73f5340e4
        webhook_url: https://my.api/events/
        _links:
          self:
            href: https://api.ubble.ai/v2/face-authentications/fav_tkoi5db4hryu5cei5vwoabr7we
          applicant:
            href: https://api.ubble.ai/v2/applicants/aplt_tkoi5db4hryu5cei5vwoabr7we
    face_authentication_attempt_creation_response_body:
      value:
        id: fatp_tkoi5db4hryu5cei5vwoabrPoQ
        created_on: 2017-07-21 17:32:28+00:00
        modified_on: 2017-07-21 17:40:32+00:00
        status: pending_redirection
        response_codes: []
        phone_number:
          country_code: '+1'
          number: '2068133616'
        client_information:
          pre_selected_residence_country: FR
        redirect_url: https://myweb.site?query-param=hello
        _links:
          self:
            href: https://api.ubble.ai/v2/face-authentications/fav_tkoi5db4hryu5cei5vwoabr7we/attempts/fatp_tkoi5db4hryu5cei5vwoabr7we
          verification_url:
            href: https://id.ubble.ai/4hryu5cei5/
    face_authentication_attempt_assets_response_body:
      value:
        data:
        - _links:
            asset_url:
              href: https://storage-b.env.ubble.ai/ubble-ai/NDYOOVHGZPAQ/a54b3393-f02a-47c9-a9c5-2f6ee73560e1/bb603e2f-5de9-40f2-9631-8285a33c24c0/tight_crops/FRA-I5-Front-bb603e2f-5de9-40f2-9631-8285a33c24c0-1679921906596.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=V9jgOdpOdeVSFTkA4ZsG%2F20230327%2Feu-west-2%2Fs3%2Faws4_request&X-Amz-Date=20230327T163228Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=87d8467ab92cbad7c00171af28e613d495f3ff441ce0ea59dd013d68abc50555
          type: face_image
        - _links:
            asset_url:
              href: https://storage-b.env.ubble.ai/ubble-ai/NDYOOVHGZPAQ/a54b3393-f02a-47c9-a9c5-2f6ee73560e1/bb603e2f-5de9-40f2-9631-8285a33c24c0/tight_crops/FRA-I5-Front-bb603e2f-5de9-40f2-9631-8285a33c24c0-1679921906596.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=V9jgOdpOdeVSFTkA4ZsG%2F20230327%2Feu-west-2%2Fs3%2Faws4_request&X-Amz-Date=20230327T163228Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=87d8467ab92cbad7c00171af28e613d495f3ff441ce0ea59dd013d68abc50555
          type: face_video
        _links:
          self:
            href: https://api.ubble.ai/api/v2/face-authentications/fau_116kcr6z00h62kzvf4hw2twb3b/attempts/fatp_116kcr6z00h62kzvf4hw2twb3d/assets
        limit: 10
        skip: 0
        total_count: 2
    attempt_creation_request_body_min:
      value:
        redirect_url: https://myweb.site?query-param=hello
    face_authentication_attempt_get_response_body:
      value:
        id: fatp_tkoi5db4hryu5cei5vwoabrPoQ
        created_on: 2017-07-21 17:32:28+00:00
        modified_on: 2017-07-21 17:40:32+00:00
        phone_number:
          country_code: '+1'
          number: '2068133616'
        redirect_url: https://myweb.site?query-param=hello
        status: checks_in_progress
        response_codes: []
        client_information:
          pre_selected_residence_country: FR
        applicant_session_information:
          ip_address: 123.123.123.01
        _links:
          self:
            href: https://api.ubble.ai/v2/face-authentications/fav_tkoi5db4hryu5cei5vwoabr7we/attempts/fatp_tkoi5db4hryu5cei5vwoabr7we
          verification_url:
            href: https://id.ubble.ai/4hryu5cei5/
    face_authentication_anonymization_response_body:
      value:
        id: fav_tkoi5db4hryu5cei5vwoabr7we
        created_on: 2017-07-21 17:32:28+00:00
        modified_on: 2017-07-21 17:40:32+00:00
        user_journey_id: usj_tkoi5db4hryu5cei5vwoabr7we
        applicant_id: aplt_tkoi5db4hryu5cei5vwoabr7we
        status: declined
        response_codes:
        - code: 62403
          summary: consent_unclear
        - code: 61402
          summary: face_video_lighting_issue
        risk_labels:
        - multiple_faces_detected
        webhook_url: https://my.api/events/
        _links:
          self:
            href: https://api.ubble.ai/v2/face-authentications/face_tkoi5db4hryu5cei5vwoabr7we
          applicant:
            href: https://api.ubble.ai/v2/applicants/aplt_tkoi5db4hryu5cei5vwoabr7we
    face_attempt_creation_request_body_max:
      value:
        phone_number:
          country_code: '+1'
          number: '2068133616'
        client_information:
          pre_selected_residence_country: FR
        redirect_url: https://myweb.site?query-param=hello
  parameters:
    skipParam:
      name: skip
      in: query
      description: Number of items to skip (offset)
      required: false
      schema:
        type: integer
        minimum: 0
        default: 0
    limitParam:
      name: limit
      in: query
      description: Maximum number of items to return per page
      required: false
      schema:
        type: integer
        minimum: 1
        default: 10
x-tagGroups:
- name: Endpoints documentation
  tags:
  - Applicants
  - Business applicants
  - Identity verifications
  - ID document verifications
  - Face authentications
  - AML verifications
  - Website verifications (Coming soon)
  - Bank document verifications (Coming soon)
  - Company document verifications (Coming soon)
  - Address document verifications (Coming soon)
  - Service status
